CREATE TABLE profiles_new
(
    id                      SERIAL PRIMARY KEY,
    username                VARCHAR(50) UNIQUE  NOT NULL,
    nickname                VARCHAR(50),
    email                   VARCHAR(255) UNIQUE NOT NULL,
    hashed_password         VARCHAR(255)        NOT NULL,
    bio                     TEXT,
    profile_pic_path        TEXT,
    current_game            VARCHAR(100),
    is_online               BOOLEAN,
    win_loss_ratio_TTT      DOUBLE PRECISION DEFAULT 0.0,
    win_loss_ratio_connect4 DOUBLE PRECISION DEFAULT 0.0,
    win_loss_ratio_checkers DOUBLE PRECISION DEFAULT 0.0,
    rating_TTT              INT              DEFAULT 0,
    rating_connect4         INT              DEFAULT 0,
    rating_checkers         INT              DEFAULT 0,
    rank_TTT                VARCHAR(50)      DEFAULT 'unranked',
    rank_connect4           VARCHAR(50)      DEFAULT 'unranked',
    rank_checkers           VARCHAR(50)      DEFAULT 'unranked',
    wins_TTT                INT              DEFAULT 0,
    wins_connect4           INT              DEFAULT 0,
    wins_checkers           INT              DEFAULT 0,
    games_played            JSONB,
    achievement_progress    JSONB,
    friends                 JSONB,
    friend_requests         JSONB,
    created_at              TIMESTAMP        DEFAULT CURRENT_TIMESTAMP
);

